apiVersion: apps/v1
kind: Deployment
metadata:
  name: guts-scoreboard
  namespace: bmt-guts-scoreboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guts-scoreboard
  template:
    metadata:
      labels:
        app: guts-scoreboard
    spec:
      containers:
      - env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: guts-scoreboard-postgres-app
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              key: password
              name: guts-scoreboard-postgres-app
        - name: DATABASE_URL
          value: postgres://$(DB_USER):$(DB_PASS)@guts-scoreboard-postgres-rw:5432/guts_scoreboard
        - name: RUST_LOG
          value: tower_http=trace
        envFrom:
        - secretRef:
            name: guts-scoreboard
        image: ghcr.io/berkeleymt/guts-scoreboard:latest
        name: guts-scoreboard
        ports:
        - containerPort: 4887
        resources:
          limits:
            memory: 4Gi
          requests:
            cpu: 200m
            memory: 64Mi
      imagePullSecrets:
      - name: ghcr-auth
